## TF-IDF

#### Term Frequency (TF)

In [1]:
import pandas as pd
import numpy as np
import re

In [13]:
corpus = [
    "I love to eat pizza because pizza is tasty",
    "Pizza is very delicious",
    "I hate cold pizza"
]

### Scratch Implementation

In [14]:
def tokenize(sentence):
    sentence = sentence.lower()
    sentence = re.sub(r'[^\w\s]', '', sentence)
    return sentence.split()

Calculating TF

In [15]:
def get_term_frequency(corpus):

    vocabulary = []
    for c in corpus:
        splitted_sentence = tokenize(c)
        for word in splitted_sentence:
            vocabulary.append(word)

    vocabulary = set(vocabulary)

    term_freq = []
    for sentence in corpus:
        splitted_sentence = tokenize(sentence)
        vocab_dict = {v:0 for v in vocabulary}
        
        for word in splitted_sentence:
            vocab_dict[word] += 1
            
        for v in vocabulary:
            tf = vocab_dict[v]/len(splitted_sentence)
            vocab_dict[v] = tf
            
        term_freq.append(vocab_dict)

    return term_freq

In [16]:
term_freq = get_term_frequency(corpus)
term_freq

[{'delicious': 0.0,
  'is': 0.1111111111111111,
  'tasty': 0.1111111111111111,
  'cold': 0.0,
  'pizza': 0.2222222222222222,
  'love': 0.1111111111111111,
  'i': 0.1111111111111111,
  'because': 0.1111111111111111,
  'to': 0.1111111111111111,
  'hate': 0.0,
  'eat': 0.1111111111111111,
  'very': 0.0},
 {'delicious': 0.25,
  'is': 0.25,
  'tasty': 0.0,
  'cold': 0.0,
  'pizza': 0.25,
  'love': 0.0,
  'i': 0.0,
  'because': 0.0,
  'to': 0.0,
  'hate': 0.0,
  'eat': 0.0,
  'very': 0.25},
 {'delicious': 0.0,
  'is': 0.0,
  'tasty': 0.0,
  'cold': 0.25,
  'pizza': 0.25,
  'love': 0.0,
  'i': 0.25,
  'because': 0.0,
  'to': 0.0,
  'hate': 0.25,
  'eat': 0.0,
  'very': 0.0}]

In [17]:
df = pd.DataFrame(term_freq)
df.index = corpus

display(df)

,delicious,is,tasty,cold,pizza,love,i,because,to,hate,eat,very
I love to eat pizza because pizza is tasty,0.00,0.111111,0.111111,0.00,0.222222,0.111111,0.111111,0.111111,0.111111,0.00,0.111111,0.00
Pizza is very delicious,0.25,0.250000,0.000000,0.00,0.250000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.25
I hate cold pizza,0.00,0.000000,0.000000,0.25,0.250000,0.000000,0.250000,0.000000,0.000000,0.25,0.000000,0.00

#### Inverse Document Frequency (IDF)

In [18]:
def get_inverse_document_frequency(corpus):
    vocabulary = []
    for c in corpus:
        sentence = tokenize(c)
        for word in sentence:
            vocabulary.append(word)

    vocabulary = set(vocabulary)

    total_documents = len(corpus)

    inverse_document_frequency = {}
    for v in vocabulary:
        num_docs = 0           # number of documents containing a word
        for sentence in corpus:
            splitted_sentence = tokenize(sentence)
            if v in splitted_sentence:
                num_docs += 1
        inverse_document_frequency[v] = np.log(total_documents/num_docs)
        
    return inverse_document_frequency

In [19]:
inverse_document_frequency = get_inverse_document_frequency(corpus)
inverse_document_frequency

{'delicious': 1.0986122886681098,
 'is': 0.4054651081081644,
 'tasty': 1.0986122886681098,
 'cold': 1.0986122886681098,
 'pizza': 0.0,
 'love': 1.0986122886681098,
 'i': 0.4054651081081644,
 'because': 1.0986122886681098,
 'to': 1.0986122886681098,
 'hate': 1.0986122886681098,
 'eat': 1.0986122886681098,
 'very': 1.0986122886681098}

Calculating TF-IDF

In [20]:
def get_tf_idf(corpus):
    tf_list = get_term_frequency(corpus)
    idf = get_inverse_document_frequency(corpus)

    tf_idf = []
    for tf_dict in tf_list:
        tf_idf_sentence = {}
        for word, term_freq in tf_dict.items():
            tf_idf_sentence[word] = term_freq * idf[word]
        tf_idf.append(tf_idf_sentence)

    return tf_idf

In [21]:
tf_idf = get_tf_idf(corpus)
tf_idf

[{'delicious': 0.0,
  'is': 0.04505167867868493,
  'tasty': 0.12206803207423442,
  'cold': 0.0,
  'pizza': 0.0,
  'love': 0.12206803207423442,
  'i': 0.04505167867868493,
  'because': 0.12206803207423442,
  'to': 0.12206803207423442,
  'hate': 0.0,
  'eat': 0.12206803207423442,
  'very': 0.0},
 {'delicious': 0.27465307216702745,
  'is': 0.1013662770270411,
  'tasty': 0.0,
  'cold': 0.0,
  'pizza': 0.0,
  'love': 0.0,
  'i': 0.0,
  'because': 0.0,
  'to': 0.0,
  'hate': 0.0,
  'eat': 0.0,
  'very': 0.27465307216702745},
 {'delicious': 0.0,
  'is': 0.0,
  'tasty': 0.0,
  'cold': 0.27465307216702745,
  'pizza': 0.0,
  'love': 0.0,
  'i': 0.1013662770270411,
  'because': 0.0,
  'to': 0.0,
  'hate': 0.27465307216702745,
  'eat': 0.0,
  'very': 0.0}]

In [22]:
df = pd.DataFrame(tf_idf)
df.index = corpus
display(df)

,delicious,is,tasty,cold,pizza,love,i,because,to,hate,eat,very
I love to eat pizza because pizza is tasty,0.000000,0.045052,0.122068,0.000000,0.0,0.122068,0.045052,0.122068,0.122068,0.000000,0.122068,0.000000
Pizza is very delicious,0.274653,0.101366,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.274653
I hate cold pizza,0.000000,0.000000,0.000000,0.274653,0.0,0.000000,0.101366,0.000000,0.000000,0.274653,0.000000,0.000000

### Using sk-learn

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
tf_idf_vectorizer = TfidfVectorizer()

In [34]:
tf_idf_rep = tf_idf_vectorizer.fit_transform(corpus).todense()

In [36]:
tf_idf_rep

matrix([[0.37867627, 0.        , 0.        , 0.37867627, 0.        ,
         0.28799306, 0.37867627, 0.44730461, 0.37867627, 0.37867627,
         0.        ],
        [0.        , 0.        , 0.5844829 , 0.        , 0.        ,
         0.44451431, 0.        , 0.34520502, 0.        , 0.        ,
         0.5844829 ],
        [0.        , 0.65249088, 0.        , 0.        , 0.65249088,
         0.        , 0.        , 0.38537163, 0.        , 0.        ,
         0.        ]])

In [37]:
df = pd.DataFrame(tf_idf_rep)
df.columns = tf_idf_vectorizer.get_feature_names_out()
df.index = corpus
display(df)

,because,cold,delicious,eat,hate,is,love,pizza,tasty,to,very
I love to eat pizza because pizza is tasty,0.378676,0.000000,0.000000,0.378676,0.000000,0.287993,0.378676,0.447305,0.378676,0.378676,0.000000
Pizza is very delicious,0.000000,0.000000,0.584483,0.000000,0.000000,0.444514,0.000000,0.345205,0.000000,0.000000,0.584483
I hate cold pizza,0.000000,0.652491,0.000000,0.000000,0.652491,0.000000,0.000000,0.385372,0.000000,0.000000,0.000000

For a large corpus, the vocabulary can be huge, hence computation and storage of both BOW and TF-IDF can be difficult.